# Don't print a new line at the start of the prompt
add_newline = false

# Replace the "❯" symbol in the prompt with "➜"
[character]      # The name of the module we are configuring is "character"
symbol = "➜"     # The "symbol" segment is being set to "➜"
success_symbol = "[➜](bold green) "
error_symbol = "[✗](bold red) "


[directory]
truncation_length = 8
truncation_symbol = "…/"

[gcloud]
format = 'on [$symbol$account(\($project\))]($style) '

[git_status]
conflicted = "🏳"
ahead = "🏎💨"
behind = "😰"
diverged = "😵"
untracked = "🤷‍"
stashed = "📦"
modified = "📝"
staged = '[++\($count\)](green)'
renamed = "👅"
deleted = "🗑"

[aws]
symbol = " "

[battery]
full_symbol = "🔋"
charging_symbol = "⚡️"
discharging_symbol = "💀"

[conda]
symbol = " "

[dart]
symbol = " "

[docker]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

[haskell]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[memory_usage]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "


[python]
disabled = true

[terraform]
format = "[🚀 $workspace]($style) "

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true
